---
title: "Validate NHTS BESTMILES estimates against HPMS"
author: "Liming Wang, Huajie Yang"
date: "1/18/2017"
output: html_document
---

```{r setup, include=F}
knitr::opts_knit$set(root.dir = "../")
knitr::opts_chunk$set(message=FALSE, warning=F)
options(width = 2000)

if (!require("pacman")) {install.packages("pacman"); library(pacman)}
pacman::p_load(dplyr, ggplot2, knitr, tidyr, readxl, stringr, readr, scales)
```

```{r load_data, include=F}
source('code/functions.R')
source('code/load_data.R')

hh.df_file <- "output/intermediate/hh_df.rda"
hh.df <- load_or_source(hh.df_file, "hh.df")

# Souce:  https://www.fhwa.dot.gov/policyinformation/statistics/2010/hm71.cfm 
HPMS.VMT <- read_excel("data/Highway Statistics VMT.xlsx")

Transit.. <- read.csv( "data/Brian.Gregor/Ubz_Comparisons.csv" )
pop.transit.df <- Transit.. %>%
              dplyr::select(UZA=Name, pop.transit=Population) %>%
              group_by(UZA) %>%
              summarise(pop.transit=first(pop.transit))

```

## NHTS

Compute annual VMT per capita from the BESTMILE and HHSIZE variable in 2009 NHTS, weighted by household weights (WTHHFIN):
$AVMTcap_{uza} = \frac{\sum_{i \in uza}{BESTMILE_i * WTHHFIN_i}}{\sum_{i \in uza}{HHSIZE_i * WTHHFIN_i}}$

```{r}
AVMTcap.df <- hh.df %>%
        dplyr::select(HOUSEID, BESTMILE, HHSIZE, UZA, WTHHFIN) %>%
        group_by(UZA) %>%
        summarise(AVMTcap=sum(BESTMILE * WTHHFIN, na.rm=T) / sum(HHSIZE * WTHHFIN, na.rm=T)) %>%
        arrange(UZA)

#head(AVMTcap.df)
```


## HPMS

2010 HPMS total annual VMT divided by UZA population:

$AVMTcap_{uza} = \frac{TotDVMT_{uza} * 365 * 1000}{TotPop_{uza}}$

```{r, include=F}
# HPMS data 
HPMS.VMT <- HPMS.VMT %>%
        mutate(UrbanizedArea=str_replace_all(UrbanizedArea, "--", "-"),
               UZA=paste(UrbanizedArea, State, sep=","),
               TotAVMT=TotDVMT*1000*365,
               UZA=recode(UZA, 
                          "Allentown-Bethlehem, PA"="Allentown-Bethlehem, PA-NJ",
                          "Boston, MA"="Boston, MA-NH-RI",
                          "Bridgeport-Stamford, CT"="Bridgeport-Stamford, CT-NY",
                          "Charlotte, NC"="Charlotte, NC-SC",
                          "Chicago, IL"="Chicago, IL-IN",
                          "Cincinnati, OH"="Cincinnati, OH-KY-IN",
                          "El Paso, TX"="El Paso, TX-NM",
                          "Kansas City, MO"="Kansas City, MO-KS",
                          "Louisville, KY"="Louisville, KY-IN", 
                          "Memphis, TN"="Memphis, TN-MS-AR",
                          "New York-Newark, NY"="New York-Newark, NY-NJ-CT",
                          "Omaha, NE"="Omaha, NE-IA",
                          "Pensacola, FL"="Pensacola, FL-AL", 
                          "Philadelphia, PA"="Philadelphia, PA-NJ-DE-MD",
                          "Portland, OR"="Portland, OR-WA",
                          "Providence, RI"="Providence, RI-MA",
                          "Spokane, WA"="Spokane, WA-ID",
                          "Springfield, MA"="Springfield, MA-CT",
                          "St. Louis, MO"="St. Louis, MO-IL",
                          "Toledo, OH"="Toledo, OH-MI", 
                          "Washington, DC"="Washington, DC-VA-MD", 
                          "Worcester, MA"="Worcester, MA-CT")) %>%
        dplyr::select(UZA, TotAVMT) %>%
        arrange(UZA)

UA <- read_csv("data/Census/ua_list_ua.csv")
UA <- UA %>% mutate(NAME2=str_replace_all(NAME, "--", "-"),
                    NAME2 = recode(NAME2,
                                       "Aberdeen-Bel Air South-Bel Air North, MD"="Aberdeen-Havre de Grace-Bel Air, MD",
                                       "Albany-Schenectady, NY" = "Albany, NY",
                                       "Allentown, PA-NJ" = "Allentown-Bethlehem, PA-NJ",
                                       "Augusta-Richmond County, GA--SC"  = "Augusta-Richmond County, GA-SC",
                                       "Benton Harbor-St. Joseph-Fair Plain, MI" = "Benton Harbor-St. Joseph, MI", 
                                       "Bonita Springs, FL" = "Bonita Springs-Naples, FL",
                                       #"Brooksville, FL"
                                       "Cumberland, MD-WV-PA" = "Cumberland, MD--WV",
                                       #"Danville, IL", ##??
                                       "Palm Coast-Daytona Beach-Port Orange, FL" = "Daytona Beach-Port Orange, FL",
                                       "El Centro-Calexico, CA" = "El Centro, CA",
                                       "Fayetteville-Springdale-Rogers, AR-MO" = "Fayetteville-Springdale, AR",
                                       "Fort Walton Beach-Navarre-Wright, FL" = "Fort Walton Beach, FL",
                                       "Gulfport, MS" = "Gulfport-Biloxi, MS",
                                       "Urban Honolulu, HI" = "Honolulu, HI",
                                       "Indio-Cathedral City, CA" = "Indio-Cathedral City-Palm Springs, CA",
                                       "Kennewick-Pasco, WA" = "Kennewick-Richland, WA",
                                       "Kenosha, WI-IL" = "Kenosha, WI",
                                       "Las Vegas-Henderson, NV" = "Las Vegas, NV",
                                       "Leesburg-Eustis-Tavares, FL" = "Leesburg-Eustis, FL",
                                       "Los Angeles-Long Beach-Anaheim, CA" = "Los Angeles-Long Beach-Santa Ana, CA",
                                       "Louisville/Jefferson County, KY-IN" = "Louisville, KY-IN",
                                       "Minneapolis-St. Paul, MN-WI" = "Minneapolis-St. Paul, MN",
                                       "Monessen-California, PA" = "Monessen, PA",
                                       "Myrtle Beach-Socastee, SC-NC" = "Myrtle Beach, SC",
                                       "North Port-Port Charlotte, FL" = "North Port-Punta Gorda, FL",
                                       "Norwich-New London, CT-RI" = "Norwich-New London, CT",
                                       "Poughkeepsie-Newburgh, NY-NJ" = "Poughkeepsie-Newburgh, NY",
                                       "Raleigh-Durham, NC" = "Raleigh, NC",
                                       "Reno, NV-CA" = "Reno, NV",
                                       #"Sandusky, OH"
                                       "Salt Lake City-West Valley City, UT" = "Salt Lake City, UT",
                                       "Seaside-Monterey, CA" = "Seaside-Monterey-Marina, CA",
                                       "South Lyon-Howell, MI" = "South Lyon-Howell-Brighton, MI",
                                       "Spokane, WA" = "Spokane, WA-ID",
                                       #"St. Charles, MD"
                                       "Sebastian-Vero Beach South-Florida Ridge, FL" = "Vero Beach-Sebastian, FL",
                                       "Victorville-Hesperia, CA" = "Victorville-Hesperia-Apple Valley, CA",
                                       "Westminster-Eldersburg, MD" = "Westminster, MD"
                        )
  )

HPMS.VMT <- HPMS.VMT %>% 
  left_join(UA %>% select(NAME2, POP), by=c("UZA"="NAME2")) %>% 
  mutate(AVMTcap=TotAVMT/POP)
```


## Comparison 
```{r, echo=F}
VMT_diff.df <- AVMTcap.df %>%
        left_join(HPMS.VMT, by="UZA", suffix=c(".NHTS", ".HPMS")) %>%
        filter(complete.cases(.)) %>%
        mutate(abs_diff=AVMTcap.NHTS - AVMTcap.HPMS,
               `% diff`=abs_diff/AVMTcap.HPMS*100
               ) %>%
        select(-TotAVMT, -POP) %>% 
        arrange(desc(abs(`% diff`))) %>%
        as.data.frame()
knitr::kable(VMT_diff.df)
```

```{r}
histogram.pct(VMT_diff.df$abs_diff, x.lab="absolute different in annual VMT per capita")
histogram.pct(VMT_diff.df$`% diff`, x.lab="% different in annual VMT per capita")

```


